### ISSUE TITLE
Consider an API to clear the textbox

### ISSUE THREAD

**Issue by xjamundx** [rackt/react-autocomplete#56]
I can't figure out a way to set the state to empty without manually deleting the characters. Probably I'm doing something crazy, but it might be nice if we could programmatically clear (or just set the value). Not sure the best way to do it.

**Comment by xjamundx** [comment]
Oh this is a dup of #49

**Comment by akaashanky** [comment]
Definitely not the most elegant way to do it, but by assigning a ref to the Autocomplete component, you can get access to its setState method. After which, you can modify the value field of the state as you see fit.

```
this.refs.yourRef.setState({value: ''});
```
Again, this is a terrible way to get the job done, but can be used until we have API support.
